analytics_platform:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 9000
      database: analytics
      user: admin
      password: password
      schema: analytics
      cluster: null
      secure: false
      verify: false