analytics_platform:
  target: dev
  outputs:
    dev:
      type: spark
      method: odbc
      host: spark-master
      port: 10000
      database: iceberg_catalog
      schema: analytics
      auth: None