version: 2

sources:
  - name: iceberg
    description: "Raw data from Apache Iceberg data lake"
    database: spark_catalog
    schema: warehouse
    meta:
      connection: spark
      type: data_lake
    tables:
      - name: customers
        description: "Raw customer data from source PostgreSQL database"
        identifier: "customers"
        loaded_at_field: created_at
        columns:
          - name: id
            description: "Primary key for customers table"
            tests:
              - not_null
              - unique
          - name: name
            description: "Customer full name"
            tests:
              - not_null
          - name: email
            description: "Customer email address"
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_unique
          
      - name: orders
        description: "Raw order transactions from source system"
        identifier: "orders"
        loaded_at_field: created_at
        columns:
          - name: id
            description: "Primary key for orders table"
            tests:
              - not_null
              - unique
          - name: customer_id
            description: "Foreign key to customers table"
            tests:
              - not_null
              - relationships:
                  to: ref('stg_customers')
                  field: customer_id
          - name: amount
            description: "Order amount in USD"
            tests:
              - not_null
              - dbt_expectations.expect_column_values_to_be_between:
                  min_value: 0
          - name: status
            description: "Order status"
            tests:
              - accepted_values:
                  values: ['pending', 'completed', 'cancelled', 'refunded']
                  
      - name: payments
        description: "Raw payment transactions"
        identifier: "payments"
        loaded_at_field: created_at
        columns:
          - name: id
            description: "Primary key for payments table"
            tests:
              - not_null
              - unique
          - name: order_id
            description: "Foreign key to orders table"
            tests:
              - not_null
              - relationships:
                  to: ref('stg_orders')
                  field: order_id
          - name: amount
            description: "Payment amount"
            tests:
              - not_null
          - name: payment_method
            description: "Payment method used"
            tests:
              - not_null
          - name: status
            description: "Payment status"
            tests:
              - accepted_values:
                  values: ['pending', 'completed', 'failed', 'refunded']